language: ruby
rvm:
- 2.4.0
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec
env:
  secure: bR6W5vkozuq74dW8/TNHx3zNWiOXvJL2YQIQ8/p9xJULHKf/eMoAbxLZizFNVsYoLkXZre3zAf7N9Id05NcbO1JEFBYDBaTTvI9j2aUgTp+xnSP6/7AmvXSqNEbLqszQ9p+ZyivJ9n5ymv4vl+qxj2kUjIk6piPd2u+7ltB4HgxGNaPIOICkKRJPIXSYhjd1w5HOb9VGSTGQhsralnEhVowHmJynV0GYI8AZtksh2BX5zbLl0SgIJrAv4pwW0jtk4z9KkPDK7Nq2fG0KM4EvqyRJu84F6FpxSRgjjOQ7KnUu7fCBZiDPLSmsV+Bru8UrABYK8zSTHFWk3ChHfWgyjyG2tyk3KjjVf4khzveGAmM+2f4XGqBY8OcS0DTxAUPiLfsu3E3COr29aVb31k7vKUckAuSRk1ui0jBzlsFXeHk+4WUzolNoDsmRM9z9cdMnCF7zB8j0UMzCtLIz76hqwz333CAdQDbSyimmXEEUa5eewmguCYKZJO6ht1qj6q0cyZecs4P0HqZzT/5Kbll3q2Iz5aiNC+hFtB7od6yg4j31x3dqZUyx481cxjvJiAjigs9H1w5yL99NWOoYe6/N92pTr5+OtedXLBLTRkN6LCyW79reUMQc2T9fZ4mMRjYWs0wI3gdWFqSCsN53h6g3Wzq8biSrrSAFrCNpNWojgr0=
