language: ruby
rvm:
  - 1.27.0

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database mydb_test'
bundler_args: --binstubs=./bundler_stubs
