language: ruby
rvm:
- 2.4.0
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec
env:
  secure: Grg4wsJLcCQuGSK+P/WcazN/mzb9B2jgW5UXeoNmSrdCKk0SNHRgENEKK6j2vERXmaI2BrzRQd5mxY7MbzY90Ye9L70PQwyGF+5iU2nhFZOHqfZUDvM9SAnzYGWN5tgebmfadm3HOPnDcIRSJZGCrTnzKLqqYy3ZxKCLJV5d7EwoZiThF43ZO3VpEB8a9YmbAGCSXfzEZef/7kYGnHaBUitHosmpNTSAZKyOQICix/ZN18bKn2v/TOShAAlRF/WLpLfoQ5S8IZX1wnr64WamNntfovtDlwuefqyPBbbS5g+mPpKSoXVYWR4r1JqUFFNmLMK2FlGRr4f1bvn8nDGnOp2PkVV6IlCJDa1HMpZUfa1C5BpsabPIAf0cM4iavbd9fEMLJjOkXONg9sjiXNShyS2kfSb82EG0hgTbLE6OCnLVd640MSNUD++qGxYJbBzPLPBUCuyaV+u3/0kGZlSpmVsXQziSAoBkwS7+W5fZseRiaLKWw4PC0q022Vdniv/iCWGOjC5zj+GvgVsijBWNIveYbcbP//B5Z7oirYuFE6cZIRmchnzCX0j6U7ky//+j6cRRRtqn3PIzw+3qqtp8K+8zo0MbMlwapU9sgfaI90eVUeBRYx8AeCeH2UB9R8Z25ZusHjK48+12fvRWTpibB8PnTjymqtANCTPzYYdg+ec=
