test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:amazon, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:amazon, :secret_access_key) %>
  region: eu-central-1
  bucket: <%= Rails.application.credentials.dig(:amazon, :bucket) %>
